import type { Metadata } from "next";

import { Providers } from "@app/app/providers";
import MainLayout from '@app/components/layout /main-layout';
import MainContainer from '@app/components/layout /main-container';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <MainContainer>
            <MainLayout>
              {children}
            </MainLayout>
          </MainContainer>
        </Providers>
      </body>
    </html>
  );
}
